---
title: "General Trends"
execute:
  echo: false
format: html
---

## State

```{r}
#| warning: false
library(ggplot2)
library(dplyr)
df <- read.csv("data/cleaned_data/data_cleaned.csv")
ggplot(df, aes(x = reorder(State, table(State)[State]), fill = Decision)) +
  geom_bar() + coord_flip() + 
  theme_classic() + scale_fill_manual(values = c("Admit" = "yellowgreen", "Waitlist" = "gray90", 
"Decline" = "firebrick"))  +
labs(title = "Decision Proportions Vary by State",
       x = "State", 
       y = "Number of Students", 
       fill = "Decision") 
```

## Gender

```{r}
#| warning: false
df_percent <- df %>%
  mutate(Gender = factor(Gender, levels = c(0, 1), labels = c("Male", "Female"))) %>% 
  group_by(Gender, Decision) %>%
  summarise(count = n()) %>%
  group_by(Gender) %>%
  mutate(percentage = count / sum(count) * 100) %>%
  ungroup()

ggplot(df_percent, aes(x = reorder(Gender, -percentage), y = percentage, fill = Decision)) +
  geom_bar(stat = "identity") + 
  coord_flip() +
  theme_classic() +
  scale_fill_manual(values = c("Admit" = "yellowgreen", "Waitlist" = "gray90", 
                               "Decline" = "firebrick")) +
  labs(title = "Decision Proportions are Nearly Identical Across Genders",
       x = "Gender", 
       y = "Percentage of Students", 
       fill = "Decision") +
  geom_text(aes(label = paste0(round(percentage, 1), "%")), 
            position = position_stack(vjust = 0.5),
            size = 4, color = "black") 
```

## 
