---
title: "Untitled"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(ggplot2)
library(gt)
```

```{r}
data <- read.csv("../data/cleaned_data/data_cleaned.csv")
```

```{r}
data %>%
  mutate(Decision = fct_relevel(Decision, "Admit", "Waitlist", "Decline")) %>%
  summarize("Test Score" = mean(TestScore), "Writing Score" = mean(WritingScore), "GPA" = mean(GPA)) %>%
  gt() %>%
  fmt_number(
    columns = c(`GPA`), 
    decimals = 2,
    use_seps = FALSE
  ) %>%
  fmt_number(
    columns = c(`Test Score`, `Writing Score`), 
    decimals = 1,
    use_seps = FALSE
  ) %>%
  tab_header(title = md("Average Scores for all students"))

```

```{r}
data %>%
  mutate(Decision = fct_relevel(Decision, "Admit", "Waitlist", "Decline")) %>%
  group_by(Decision) %>%
  summarize("Test Score" = mean(TestScore), "Writing Score" = mean(WritingScore), "GPA" = mean(GPA)) %>%
  gt() %>%
  fmt_number(
    columns = c(`GPA`), 
    decimals = 2,
    use_seps = FALSE
  ) %>%
  fmt_number(
    columns = c(`Test Score`, `Writing Score`), 
    decimals = 1,
    use_seps = FALSE
  )%>%
  tab_header(title = md("Average Scores for students by decision"))
```

```{r}
data %>%
  mutate(Decision = fct_relevel(Decision, "Admit", "Waitlist", "Decline")) %>%
  group_by(Decision) %>%
  ggplot() + geom_boxplot(aes(Decision, GPA)) + theme_bw()
```

```{r}
data %>%
  mutate(Decision = fct_relevel(Decision, "Admit", "Waitlist", "Decline")) %>%
  group_by(Decision) %>%
  ggplot() + geom_boxplot(aes(Decision, TestScore)) + theme_bw()
```

```{r}
data %>%
  mutate(Decision = fct_relevel(Decision, "Admit", "Waitlist", "Decline")) %>%
  group_by(Decision) %>%
  ggplot() + geom_boxplot(aes(Decision, WritingScore))
```

```{r}
data %>%
  mutate(Decision = fct_relevel(Decision, "Admit", "Waitlist", "Decline")) %>%
  ggplot() + geom_point(aes(x=GPA, y=TestScore, color = Decision)) + scale_color_manual(values = c("chartreuse4", "darkgoldenrod2", "brown3")) + theme_minimal()
```

```{r}
data %>%
  mutate(Decision = fct_relevel(Decision, "Admit", "Waitlist", "Decline")) %>%
  ggplot() + geom_point(aes(x=WritingScore, y=TestScore, color = Decision)) + scale_color_manual(values = c("chartreuse4", "darkgoldenrod2", "brown3")) + theme_minimal()
```

```{r}
data %>%
  mutate(Decision = fct_relevel(Decision, "Admit", "Waitlist", "Decline")) %>%
  ggplot() + geom_point(aes(x=GPA, y=WritingScore, color = Decision)) + scale_color_manual(values = c("chartreuse4", "darkgoldenrod2", "brown3")) + theme_minimal()
```

```{r}
library(corrr)
data %>%
  subset(select = -X) %>%
  correlate() %>% 
  focus(TestScore) %>%
  gt() %>%
  tab_style(
    style = list(
      cell_fill(color = "seagreen2"),
      cell_text(weight = "bold")
      ),
    locations = cells_body(
      columns = TestScore,
      rows = TestScore >= 0.6
    )) %>%
  tab_style(
    style = list(
      cell_fill(color = "coral1"),
      cell_text(weight = "bold")
      ),
    locations = cells_body(
      columns = TestScore,
      rows = TestScore <= -0.1
    )) %>%
  cols_label(
    term = "Variable",
    TestScore = "Correlation",
  ) %>%
  tab_header(
    title = md("Correlation of Test Score with all other variables "),
  )
```
