project:
  type: website
  resources: images/coverreal.png

website:
  title: "2025 Student Internship Report"
  navbar:
    left:
#      - href: index.qmd
#        text: Home
      - href: introduction.qmd
        text: Introduction
      - href: general_trends.qmd
        text: Data Overview and Trends
      - href: admit_trends.qmd
        text: Admit Trends
      - href: waitlist_decline.qmd
        text: Waitlist and Decline Trends
      - href: recommendations.qmd
        text: Recommendations

format:
  html:
    theme: 
      - styles.scss
    toc: true



